import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync('js/main.js','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const stack=fs.readFileSync('js/stackManager.js','utf8');
const css=fs.readFileSync('css/mobile.css','utf8');
const base=fs.readFileSync('css/style.css','utf8');
const coin=fs.readFileSync('js/startingCoin.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('build-manifest.json','utf8'));
assert.equal(manifest.softMatchLifecycle,'idempotent board teardown/setup; no duplicate deck/graveyard/exile DOM across matches');
assert.equal(manifest.matchInitializationCover,'black spinner cover until starting coin is mounted');
assert.match(manifest.mobileHandGeometry,/5:7 fixed-size local hand cards/);
assert.match(manifest.mobilePriorityHud,/priority status above phase bullets/);
assert.match(ui,/export function teardownBoardLayout\(\{ clearGameplay = false \} = \{\}\)/);
assert.match(ui,/fieldZone\.querySelectorAll\('\.zone-row-container'\)\.forEach\(node => node\.remove\(\)\)/);
assert.match(ui,/export function setupBoardLayout\(\) \{[\s\S]*?teardownBoardLayout\(\{ clearGameplay: false \}\)/);
assert.match(main,/teardownBoardLayout\(\{ clearGameplay: true \}\);[\s\S]*?showMainMenu/);
assert.match(main,/async function initGame[\s\S]*?showMatchInitializationOverlay\(\)/);
assert.match(main,/function startMultiplayerMatch[\s\S]*?showMatchInitializationOverlay\(\)/);
assert.match(html,/id="match-loading-overlay" hidden[\s\S]*?Inicializando partida/);
assert.match(coin,/document\.body\.appendChild\(overlay\);[\s\S]*?__ARGENTINIA_HIDE_MATCH_LOADING__/);
assert.match(base,/#match-loading-overlay \{[\s\S]*?background:#000/);
assert.match(css,/\.field-zone-container \{[\s\S]*?height:36dvh !important/);
assert.match(css,/#local-hand \{[\s\S]*?height:14\.5dvh !important[\s\S]*?margin-top:auto !important[\s\S]*?align-items:flex-end/);
assert.match(css,/\.card\.attacking \{[\s\S]*?outline:4px solid #ff4338/);
assert.match(css,/\.card\.selected-blocker \{[\s\S]*?outline:4px solid #48bfff/);
assert.match(css,/grid-template-areas:[\s\S]*?"priority"[\s\S]*?"phases"/);
assert.match(css,/#turn-priority-hud \{ grid-area:priority !important; \}/);
assert.match(css,/\.turn-priority-hud \{[\s\S]*?min-height:58px/);
assert.match(css,/\.priority-owner-badge \{[\s\S]*?white-space:nowrap/);
// UI-POLISH-3 — desktop long-game overflow + humane player/stack target surfaces.
assert.match(base,/\.lands-support-wrapper > \.field-row \{ min-width: 0; \}/);
assert.match(base,/\.field-row\.desktop-overflow-scroll \{[\s\S]*?overflow-x: auto/);
assert.match(base,/\.desktop-battlefield-hover-preview \{[\s\S]*?position: fixed/);
assert.match(base,/#sidebar-hud \.player-card\.targetable \{[\s\S]*?outline: 2px solid #f1c40f/);
assert.match(ui,/DESKTOP_BATTLEFIELD_SCROLL_MIN_SCALE = 0\.88/);
assert.match(ui,/installDesktopBattlefieldScrollInteractions\(\);/);
assert.match(ui,/els\.rivalPlayerCard\?\.classList\.toggle\('targetable', allowRivalPlayerTarget\)/);
assert.match(main,/els\.rivalPlayerCard\?\.addEventListener\('click',[\s\S]*?handlePlayerTargetClick\(false\)/);
assert.doesNotMatch(main,/rivalHpBar\.parentElement\.addEventListener\('click'/);
assert.match(stack,/function getStackTargetDisplayName\(stackId\)[\s\S]*?spellStack\.find/);
assert.match(stack,/stackTargetName[\s\S]*?`Objetivo: \$\{stackTargetName\}`/);
console.log('RC5_2_MATCH_LIFECYCLE_MOBILE_HUD_CONTRACT_OK');
