import assert from 'node:assert/strict';
import fs from 'node:fs';
const css=fs.readFileSync('css/mobile.css','utf8');
const base=fs.readFileSync('css/style.css','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('build-manifest.json','utf8'));
assert.ok(['RC5.1','RC5.2'].includes(manifest.releaseCandidate));
assert.match(html,/btn-exit-game[\s\S]*assets\/images\/ui\/salir\.png/);
assert.match(base,/\.turn-controls \{ flex-direction:row/);
assert.match(css,/\.field-zone-container \{ height:35vh !important; flex:0 0 35vh/);
assert.match(css,/#local-hand \{ height:17vh !important; flex:0 0 17vh[\s\S]*align-items:flex-end/);
assert.match(css,/\.field-row \.card:not\(\.tapped\),[\s\S]*min-height:0 !important/);
assert.match(css,/#local-hand \.card\.paying,[\s\S]*transform:none !important/);
assert.match(css,/\.field-row \.card\.attacking \{ transform:none !important/);
assert.match(css,/\.field-row \.card\.selected-blocker \{ transform:none !important/);
assert.match(ui,/mobileScrollableRow[\s\S]*if \(!mobileScrollableRow\)/);
assert.match(main,/await returnToMainMenuAfterAbandon\(\)/);
assert.match(main,/resetGameplayStateForNewMatch\(\)/);
assert.match(main,/stopActiveMatchListener\(\)/);
assert.doesNotMatch(base,/store-emote-card\.premium::before/);
assert.match(base,/store-emote-card\.premium \.store-emote-art::before/);
assert.match(base,/premiumEmoteRingSpin/);
assert.doesNotMatch(base,/premiumEmoteStoreBreath/);
console.log('RC5_1_MOBILE_GEOMETRY_CONTRACT_OK');
