import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync('js/main.js','utf8');
const ui=fs.readFileSync('js/ui.js','utf8');
const css=fs.readFileSync('css/mobile.css','utf8');
const base=fs.readFileSync('css/style.css','utf8');
const coin=fs.readFileSync('js/startingCoin.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('build-manifest.json','utf8'));
assert.equal(manifest.releaseCandidate,'RC5.2');
assert.match(ui,/export function teardownBoardLayout\(\{ clearGameplay = false \} = \{\}\)/);
assert.match(ui,/fieldZone\.querySelectorAll\('\.zone-row-container'\)\.forEach\(node => node\.remove\(\)\)/);
assert.match(ui,/export function setupBoardLayout\(\) \{[\s\S]*?teardownBoardLayout\(\{ clearGameplay: false \}\)/);
assert.match(main,/teardownBoardLayout\(\{ clearGameplay: true \}\);[\s\S]*?showMainMenu/);
assert.match(main,/async function initGame[\s\S]*?showMatchInitializationOverlay\(\)/);
assert.match(main,/function startMultiplayerMatch[\s\S]*?showMatchInitializationOverlay\(\)/);
assert.match(html,/id="match-loading-overlay" hidden[\s\S]*?Inicializando partida/);
assert.match(coin,/document\.body\.appendChild\(overlay\);[\s\S]*?__ARGENTINIA_HIDE_MATCH_LOADING__/);
assert.match(base,/#match-loading-overlay \{[\s\S]*?background:#000/);
assert.match(css,/\.field-zone-container \{[\s\S]*?height:36dvh !important/);
assert.match(css,/#local-hand \{[\s\S]*?height:14\.5dvh !important[\s\S]*?margin-top:auto !important[\s\S]*?align-items:flex-end/);
assert.match(css,/\.card\.attacking \{[\s\S]*?outline:4px solid #ff4338/);
assert.match(css,/\.card\.selected-blocker \{[\s\S]*?outline:4px solid #48bfff/);
assert.match(css,/grid-template-areas:[\s\S]*?"priority"[\s\S]*?"phases"/);
assert.match(css,/#turn-priority-hud \{ grid-area:priority !important; \}/);
assert.match(css,/\.turn-priority-hud \{[\s\S]*?min-height:58px/);
assert.match(css,/\.priority-owner-badge \{[\s\S]*?white-space:nowrap/);
console.log('RC5_2_MATCH_LIFECYCLE_MOBILE_HUD_CONTRACT_OK');
