#!/usr/bin/env node
import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path'; import {execFile} from 'node:child_process'; import {promisify} from 'node:util'; import {fileURLToPath} from 'node:url';
import * as choice from '../js/headlessChoiceEngine.js'; import {buildHeadlessCoverageReport} from '../js/headlessCoverage.js'; import {beginGameRngSession,gameDeterministicId,getGameRngSnapshot,restoreGameRngSession} from '../js/gameRng.js';
const execFileAsync=promisify(execFile); const here=path.dirname(fileURLToPath(import.meta.url)); const root=path.resolve(here,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'build-manifest.json'),'utf8')); assert.equal(manifest.engineVersion,'23.19.4.15'); assert.equal(manifest.firestoreRulesVersion,'23.13.79'); assert.equal(manifest.pool,880);
assert.equal(choice.chooseModeIndex({modes:[{},{}]}),0); assert.equal(choice.chooseXValue({roughMaxX:9}),0); assert.equal(choice.chooseKicker(),false); assert.deepEqual(choice.chooseScrySurveil([1,2],'scry'),{moved:[],kept:[1,2],mode:'scry'}); assert.deepEqual(choice.chooseUntapIndexes([{index:4},{index:2}],1),[4]);
beginGameRngSession({seed:'id-test'}); const a=gameDeterministicId('token'); const snap=getGameRngSnapshot(); const b=gameDeterministicId('token'); restoreGameRngSession(snap); assert.equal(gameDeterministicId('token'),b); assert.notEqual(a,b);
const dataFiles=['criaturas.json','instantaneos.json','conjuros.json','encantamientos.json','artefactos.json','tierras.json','planeswalkers.json']; const cards=dataFiles.flatMap(source=>JSON.parse(fs.readFileSync(path.join(root,'assets/data',source),'utf8')).map(card=>({source,card}))); const report=buildHeadlessCoverageReport(cards);
assert.equal(report.total,880); assert.deepEqual(report.counts,{FULL:560,PARTIAL:302,UNSUPPORTED:18}); assert.equal(report.fullPct,63.64); assert.equal(report.structurallyKnownPct,97.95);
const ui=fs.readFileSync(path.join(root,'js/ui.js'),'utf8'); const main=fs.readFileSync(path.join(root,'js/main.js'),'utf8'); const stack=fs.readFileSync(path.join(root,'js/stackManager.js'),'utf8'); assert.match(ui,/headlessChoiceEngine/); assert.match(main,/Headless.*targets[\s\S]{0,300}candidates\[0\]/i); assert.match(stack,/gameDeterministicId\('token'\)/); assert.ok(!/const stamp=`\$\{Date\.now\(\).*Math\.random/.test(stack));
for(const f of ['js/headlessChoiceEngine.js','js/headlessCoverage.js','tools/audit_headless_coverage_23_18_2.mjs','tools/headless_full_game_worker_23_18_2.mjs','tools/run_headless_full_game_lab_23_18_2.mjs','tools/minimize_headless_failure_23_18_2.mjs','tools/register_headless_regression_candidate_23_18_2.mjs','tools/run_headless_regression_candidate_23_18_2.mjs']) assert.ok(fs.existsSync(path.join(root,f)),`missing ${f}`);
const worker=path.join(root,'tools/headless_full_game_worker_23_18_2.mjs'); async function run(){const {stdout}=await execFileAsync(process.execPath,[worker,'--seed','ci-coverage-23-18-2','--difficulty','medium','--identity','RG','--profile','coverage-v2','--maxTurns','80','--maxSteps','6000'],{maxBuffer:8*1024*1024,timeout:30000});return JSON.parse(stdout);} const r1=await run(),r2=await run(); assert.equal(r1.status,'completed'); assert.equal(r2.status,'completed'); assert.equal(r1.finalHash,r2.finalHash); assert.equal(r1.traceHash,r2.traceHash); assert.equal(r1.actionCount,r2.actionCount); assert.equal(r1.invariantFindings.length,0);
console.log(`HEADLESS_COVERAGE_FAILURE_MINIMIZER_23_18_2_OK pool=${report.total} full=${report.counts.FULL} partial=${report.counts.PARTIAL} unsupported=${report.counts.UNSUPPORTED} deterministic=PASS`);
