#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { installHeadlessDom } from './headless_dom_stub_23_18_1.mjs';
installHeadlessDom();
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const version=fs.readFileSync(path.join(root,'js/version.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'build-manifest.json'),'utf8'));
assert.match(version,/ENGINE_VERSION = '23\.18\.1'/);
assert.equal(manifest.engineVersion,'23.18.1');
assert.equal(manifest.firestoreRulesVersion,'23.13.75');
for(const f of ['js/headlessGameLab.js','js/actionReexecutor.js','tools/headless_full_game_worker_23_18_1.mjs','tools/run_headless_full_game_lab_23_18_1.mjs','tools/reexecute_headless_fixture_23_18_1.mjs','tools/reexecute_telemetry_actions_23_18_1.mjs']) assert.ok(fs.existsSync(path.join(root,f)),`missing ${f}`);
const {state,repairCombatLinksAfterZoneRemoval}=await import('../js/main.js');
const unit=(name,blockingIndex=null)=>({card:{name,instanceId:name},blockingIndex,isAttacking:false});
Object.assign(state,{activePlayer:'local',localCombat:[unit('A'),unit('B'),unit('C'),unit('D')],rivalCombat:[unit('X',0),unit('Y',1),unit('Z',3)]});
state.localCombat.splice(1,1);
repairCombatLinksAfterZoneRemoval({fromIsLocal:true,fromIndex:1});
assert.deepEqual(state.rivalCombat.map(x=>x.blockingIndex),[0,null,2],'removing attacker must clear exact blocker and rebase later indexes');
state.localCombat.splice(2,1);
repairCombatLinksAfterZoneRemoval({fromIsLocal:true,fromIndex:2});
assert.deepEqual(state.rivalCombat.map(x=>x.blockingIndex),[0,null,null],'removing newly-indexed attacker must clear its blockers');
state.rivalCombat.splice(0,1);
repairCombatLinksAfterZoneRemoval({fromIsLocal:false,fromIndex:0});
assert.deepEqual(state.rivalCombat.map(x=>x.blockingIndex),[null,null],'removing defender must not mutate attacker index space');
const main=fs.readFileSync(path.join(root,'js/main.js'),'utf8');
const stack=fs.readFileSync(path.join(root,'js/stackManager.js'),'utf8');
assert.match(main,/repairCombatLinksAfterZoneRemoval/);
assert.ok((stack.match(/repairCombatLinksAfterZoneRemoval\(/g)||[]).length>=6,'stack exits must use centralized combat rebase');
console.log('HEADLESS_FULL_GAME_23_18_1_OK version=23.18.1 blockIndexRebase=PASS rules=23.13.75');
