import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EVOLUTION_PATHS, parseEvolutionVariantId, evolutionVariantId } from '../js/evolution.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const store=read('js/store.js'), ui=read('js/ui.js'), economy=read('js/economyClient.js'), firebase=read('js/firebaseClientImpl.js'), texts=read('js/gameTexts.js'), utils=read('js/utils.js'), main=read('js/main.js');
const fail=(m)=>{throw new Error(m)};
if(EVOLUTION_PATHS.length!==20) fail(`expected 20 evolution paths, got ${EVOLUTION_PATHS.length}`);
if(new Set(EVOLUTION_PATHS.map(x=>x.baseId)).size!==20) fail('duplicate evolution base ids');
for(const p of EVOLUTION_PATHS){ if(!p.stages?.[1]||!p.stages?.[2]) fail(`missing two stages for ${p.baseId}`); if(parseEvolutionVariantId(evolutionVariantId(p.baseId,2)).stage!==2) fail(`variant roundtrip failed ${p.baseId}`); }
if(!/machine2:\s*\{\s*available:true,\s*points:2000,\s*fichas:20\s*\}/.test(store)) fail('machine2 must ship available with 2000/20 unlock default');
for(const fragment of ['maxEvolvedCardsPerDeck: 1','evolutionStage1Points: 250','evolutionStage1Fichas: 2','evolutionStage1Essence: 10','evolutionStage2Points: 500','evolutionStage2Fichas: 5','evolutionStage2Essence: 25']) if(!store.includes(fragment)) fail(`missing default ${fragment}`);
if(!economy.includes("action: 'evolveCard'")) fail('client authority action evolveCard missing');
if(!firebase.includes("runEconomyActionAuthority(uid,'cardEvolution'")) fail('firebase idempotent authority wrapper missing');
if(!/cardEvolution\s*:\s*'workshop\.evolve_card'/.test(firebase)) fail('browser recovery server-type mapping missing');
if(!/cardEvolution\s*:\s*'card-evolution'/.test(firebase)) fail('browser recovery operation prefix missing');
if(!ui.includes('openMachine2Evolution')) fail('Machine2 UI missing');
if(!ui.includes('admin-workshop-evolution-enabled')) fail('Admin evolution controls missing');
if(!utils.includes('applyEvolutionStage')) fail('runtime deck evolution baking missing');
if(!main.includes('state.userProfile && state.userProfile.evolutions')) fail('game runtime does not pass profile evolutions');
for(const key of ['workshop.evolution.title','workshop.evolution.action','admin.workshop.evolutionTitle','admin.workshop.maxEvolved']) if(!texts.includes(`'${key}'`)) fail(`Game Text key missing ${key}`);
for(const file of [ui,economy,firebase,utils,main]) if(/from\s+['"][^'"]+\?v=/.test(file)) fail('versioned ES-module import reintroduced');
console.log(`EVOLUTION_CAPSULE_23_21_6_HF23_3_14_OK paths=${EVOLUTION_PATHS.length} stages=2 authority=SERVER deckVariant=EVO1+EVO2 admin=EDITABLE`);
