import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = p => fs.readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const ui=read('js/ui.js'), admin=read('js/emotesAdmin.js'), catalog=read('js/emoteCatalog.js');
const econ=read('js/economyClient.js'), facade=read('js/firebaseClient.js'), impl=read('js/firebaseClientImpl.js'), social=read('js/multiplayerSocial.js');
const fn=fs.readFileSync(new URL('../../functions/src/index.js',import.meta.url),'utf8');
const trusted=fs.readFileSync(new URL('../../functions/src/trusted/emoteCatalog.js',import.meta.url),'utf8');
const commerce=fs.readFileSync(new URL('../../functions/src/economy/commerce.js',import.meta.url),'utf8');
const comm=fs.readFileSync(new URL('../../functions/src/multiplayer/communication.js',import.meta.url),'utf8');
const adminBackend=fs.readFileSync(new URL('../../functions/src/economy/emotes.js',import.meta.url),'utf8');
const manifest=JSON.parse(read('build-manifest.json'));
assert.match(ui,/key:\s*'emotes',\s*label:\s*'EMOTES'/); assert.match(ui,/id="admin-emotes-root"/); assert.match(ui,/mountAdminEmotesPane/); assert.match(ui,/adminSetEmoteCatalog/);
for(const field of ['ID','Nombre','Imagen','Audio','Fallback','Animación','Activo','Premium','Precio Puntos']) assert.ok(admin.includes(field),`missing Admin field ${field}`);
assert.match(admin,/Agregar emote/i); assert.match(admin,/emote_\$\{String\(i\)\.padStart\(3,'0'\)\}/); assert.match(admin,/pricePoints/);
assert.match(catalog,/EMOTE_CATALOG_MAX = 128/); assert.match(catalog,/applyEmoteCatalogSnapshot/); assert.match(catalog,/EMOTE_AUDIO_BASE/); assert.ok(catalog.includes("['webp','gif','png']"));
assert.match(econ,/economyAdminSetEmoteCatalog/); assert.match(facade,/adminSetEmoteCatalog/); assert.match(impl,/adminSetEmoteCatalogServer/);
assert.match(social,/fetchStorefrontAuthority/); assert.match(social,/applyEmoteCatalogSnapshot/); assert.match(social,/emoteAudioCandidates/);
assert.match(fn,/export const economyAdminSetEmoteCatalog = onCall/); assert.equal([...fn.matchAll(/export const \w+\s*=\s*onCall\(/g)].length,40);
assert.match(trusted,/EMOTE_CATALOG_PATH = 'gameConfig\/emotes'/); assert.match(trusted,/MAX_EMOTES = 128/); assert.match(trusted,/loadTrustedEmoteCatalog/);
assert.match(adminBackend,/setEmoteCatalogAdminTx/); assert.match(adminBackend,/admin\.emote_catalog\.set/);
assert.match(commerce,/loadTrustedEmoteCatalog\(db, tx\)/); assert.match(comm,/loadTrustedEmoteCatalog\(db, tx\)/);
assert.equal(manifest.firestoreRulesVersion,'23.13.86'); assert.equal(manifest.functionsCount,40); assert.equal(manifest.emoteCatalogAuthority,'gameConfig/emotes via economyAdminSetEmoteCatalog');
console.log('ADMIN_EMOTE_CATALOG_23_21_3_RC3_OK adminTab=YES dynamicMax=128 authority=SERVER purchase=SERVER_PRICE send=SERVER_OWNERSHIP functions=40 rules=23.13.86');
