import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const g5=read('05_Economy_Authority_Emulator_Gate/RUN_ECONOMY_AUTHORITY_EMULATOR_GATE_23_21_6_HF23_3_16_2_1.sh');
const g7=read('07_Trade_Market_Emulator_Gate/RUN_TRADE_MARKET_EMULATOR_GATE_23_21_6_HF23_3_16_2_1.sh');
const d6=read('06_Economy_Functions_DEPLOY_AFTER_GATE/DEPLOY_ECONOMY_FUNCTIONS_AFTER_GATE_23_21_6_HF23_3_16_2_1.sh');
assert.match(g5,/FUNCTIONS_DISCOVERY_TIMEOUT=30[^\n]*firebase emulators:exec/);
assert.match(g7,/FUNCTIONS_DISCOVERY_TIMEOUT=30[^\n]*firebase emulators:exec/);
assert.match(d6,/FUNCTIONS_DISCOVERY_TIMEOUT=30[^\n]*firebase deploy --only functions/);
console.log('GATE_FUNCTIONS_DISCOVERY_TIMEOUT_23_21_6_HF23_3_16_2_1_OK gate05=30s gate07=30s deploy=30s runtime=UNCHANGED');
