import assert from 'node:assert/strict';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const read=p=>fs.readFileSync(p,'utf8');
const version=await import(pathToFileURL(new URL('../js/version.js',import.meta.url).pathname).href+'?v='+Date.now());
assert.equal(version.ENGINE_VERSION,'23.19.5.6');
assert.equal(version.ECONOMY_PROTOCOL_VERSION,'econ-23.19.5.6');
assert.equal(version.ECONOMY_SCHEMA_VERSION,7);
assert.equal(version.ENGINE_PROTOCOL_VERSION,'mp-23.19.2');
assert.equal(version.FIRESTORE_RULES_VERSION,'23.13.80');
const index=read(new URL('../../functions/src/index.js',import.meta.url));
const constants=read(new URL('../../functions/src/shared/constants.js',import.meta.url));
const admin=read(new URL('../../functions/src/economy/admin.js',import.meta.url));
const audit=read(new URL('../../functions/src/economy/audit.js',import.meta.url));
const matches=read(new URL('../../functions/src/economy/matches.js',import.meta.url));
const errors=read(new URL('../../functions/src/shared/errors.js',import.meta.url));
const client=read(new URL('../js/economyClient.js',import.meta.url));
const impl=read(new URL('../js/firebaseClientImpl.js',import.meta.url));
const ui=read(new URL('../js/ui.js',import.meta.url));
const main=read(new URL('../js/main.js',import.meta.url));
const gameTexts=read(new URL('../js/gameTexts.js',import.meta.url));
const turnManager=read(new URL('../js/turnManager.js',import.meta.url));
const mobileCss=read(new URL('../css/mobile.css',import.meta.url));
const terminal=await import(pathToFileURL(new URL('../js/gameTerminal.js',import.meta.url).pathname).href+'?v='+Date.now());
const rewards=read(new URL('../js/gameRewards.js',import.meta.url));
const callables=[...index.matchAll(/export const (economy[A-Za-z0-9_]+) = onCall/g)].map(m=>m[1]).sort();
assert.equal(callables.length,25,'23.19.5.6 must expose exactly 25 economy callables');
for(const name of ['economyAdminGrant','economyAdminBulkGrant','economyAdminGetBulkGrant','economyAdminRepairGameReward','economyAdminSyncPlayerStats']) assert.ok(callables.includes(name),name);
assert.match(index,/adminEconomyAuthority: 'server'/);
assert.match(index,/economicStatisticsAuthority: 'server'/);
assert.match(index,/immutableAuditAuthority: 'server'/);
assert.match(constants,/minInstances: 0/); assert.match(constants,/maxInstances: 1/); assert.match(constants,/concurrency: 10/); assert.match(constants,/enforceAppCheck: false/);
assert.match(admin,/adminActions/); assert.match(admin,/economyEvents/); assert.match(admin,/playerStatsMirrorServer/); assert.match(admin,/adminBulkGrantReceipts/);
assert.match(admin,/BULK_PAGE_SIZE=10/); assert.match(admin,/count\(\)\.get\(\)/); assert.match(admin,/status:done\?'committed':'running'/);
assert.match(audit,/authority:'server'/); assert.match(audit,/immutable:true/); assert.match(audit,/eventSnap\.exists/);
assert.match(matches,/ensureAbandonSettlementEvidence/); assert.match(matches,/rewardReason:'abandon_penalty'/); assert.match(matches,/terminalKind:'abandon'/); assert.match(matches,/playerGameReceipts/);
assert.match(errors,/ADMIN_REWARD_REPAIR_ABANDONED/);
assert.match(client,/economyAdminGrant/); assert.match(client,/economyAdminBulkGrant/); assert.match(client,/economyAdminRepairGameReward/); assert.match(client,/economyAdminSyncPlayerStats/);
assert.match(impl,/server_owned_economic_stats/); assert.match(impl,/ADMIN_BULK_PENDING_KEY/); assert.match(impl,/adminBulkGrantServer/);
assert.match(impl,/PENDING_ABANDON_PENALTIES_KEY/); assert.match(impl,/flushPendingAbandonPenalties/);
assert.match(main,/flushPendingAbandonPenalties/); assert.ok(main.indexOf('const recoveredAbandons = await flushPendingAbandonPenalties') < main.indexOf('const recoveredRewards = await flushPendingGameRewards'),'abandon recovery must execute before positive reward recovery');
assert.doesNotMatch(main,/recordLocalAbandonStatsBestEffort/,'abandon stats must not race from the browser');
assert.doesNotMatch(turnManager,/recordPlayerGameResult/,'natural match stats must no longer race from the browser');
assert.match(matches,/ensureMatchResultStats/); assert.match(matches,/gameResultDeltas/); assert.match(matches,/terminalKind:'natural'/); assert.match(rewards,/durationMs:/);
const checkGameOverBody=turnManager.slice(turnManager.indexOf('export function checkGameOver'),turnManager.indexOf('// FASE 2'));
assert.match(checkGameOverBody,/terminalProcessedLocally/); assert.doesNotMatch(checkGameOverBody,/if \(state\.gameOver\) return;/,'synced gameOver must not suppress local terminal settlement');
assert.deepEqual(terminal.derivePerspectiveTerminalOutcome({gameOver:true,localHP:0,rivalHP:17,localPoison:0,rivalPoison:0,localDeck:[1],rivalDeck:[1],abandonedBy:null}),{won:false,reason:'hp_loss'});
assert.deepEqual(terminal.derivePerspectiveTerminalOutcome({gameOver:true,localHP:17,rivalHP:0,localPoison:0,rivalPoison:0,localDeck:[1],rivalDeck:[1],abandonedBy:null}),{won:true,reason:'hp_win'});
assert.deepEqual(terminal.derivePerspectiveTerminalOutcome({gameOver:true,localHP:20,rivalHP:20,localPoison:0,rivalPoison:0,localDeck:[],rivalDeck:[1],abandonedBy:null}),{won:false,reason:'deckout_loss'});
assert.equal(terminal.derivePerspectiveTerminalOutcome({gameOver:true,localHP:20,rivalHP:20,localPoison:0,rivalPoison:0,localDeck:[1],rivalDeck:[1],abandonedBy:'local'}),null,'explicit local abandon must never enter positive normal-loss reward flow');
assert.match(gameTexts,/'damage\.modal\.toughness': definition\('Combate', 'Resistencia actual: \{hp\}'/);
assert.match(gameTexts,/'damage\.modal\.lethal': definition\('Combate', '\(letal: \{needed\}\)'/);
assert.match(ui,/gameTextHtml\('damage\.modal\.toughness', \{ hp \}\)/); assert.match(ui,/gameTextHtml\('damage\.modal\.lethal', \{ needed \}\)/);
assert.match(mobileCss,/MOBILE SELECTED-CARD CLIPPING GUARD/); assert.match(mobileCss,/padding-top: 10px/); assert.match(ui,/rowStyles\.paddingTop/);

assert.doesNotMatch(impl,/async function logEconomyEvent\(/,'browser must not write economyEvents in 23.19.5.6');
assert.doesNotMatch(ui,/await logAdminAction\(/,'UI must not create best-effort admin audit records');
assert.match(ui,/abandon-yes\" style=\"justify-content:center; text-align:center;/);
assert.match(ui,/Penalidad de abandono sin receipt económico/); assert.match(ui,/Sin liquidación · sesión interrumpida/); assert.match(ui,/penalidad de abandono/);
assert.match(ui,/storefrontAuthorityPromise/,'Storefront load must dedupe concurrent authority requests');
assert.match(ui,/store-loading-panel/,'Storefront must render a visible loading state before authority resolves');
assert.match(ui,/STOREFRONT_LOADING_SLOW_AFTER_MS = 2800/,'Storefront slow-state threshold must match Economy Pending UX');
assert.match(ui,/store\.loading\.slow/,'Storefront must expose the slow server connection state');
assert.match(ui,/store-loading-retry/,'Storefront load failure must expose an explicit retry action');
assert.match(ui,/throwOnError: true/,'Initial Storefront render must fail visibly rather than silently presenting stale/local authority');
for (const key of ['store.loading.title','store.loading.description','store.loading.slow','store.loading.slowDescription','store.loading.errorTitle','store.loading.errorDescription','store.loading.retry']) assert.ok(gameTexts.includes(`'${key}'`),key);
const manifest=JSON.parse(read(new URL('../build-manifest.json',import.meta.url)));
assert.equal(manifest.engineVersion,'23.19.5.6'); assert.equal(manifest.economyProtocolVersion,'econ-23.19.5.6'); assert.equal(manifest.economySchemaVersion,7); assert.equal(manifest.firestoreRulesVersion,'23.13.80');
console.log('ADMIN_ECONOMY_STATISTICS_AUDIT_AUTHORITY_23_19_5_5_OK cumulative=23.19.5.6 callables=25 bulk=RESUMABLE audit=SERVER stats=SERVER abandon=SIGNED_RECEIPT+NO_POSITIVE_REPAIR+RECOVERY_JOURNAL+ROLLING_COMPAT mpTerminal=REMOTE_GAMEOVER_EXACTLY_ONCE mobile=NO_ROW_CLIP damageModal=TOKENS_RESOLVED storeLoading=SPINNER+SLOW+RETRY+DEDUPED cumulativeRules=23.13.80 appCheck=OBSERVE_ONLY');
