import assert from 'node:assert/strict';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const read = p => fs.readFileSync(p, 'utf8');
const version = await import(pathToFileURL(new URL('../js/version.js', import.meta.url).pathname).href + '?v=' + Date.now());
assert.equal(version.ENGINE_VERSION, '23.20.0');
assert.equal(version.ECONOMY_PROTOCOL_VERSION, 'econ-23.19.5.6');
assert.equal(version.ECONOMY_SCHEMA_VERSION, 8);
assert.equal(version.FIRESTORE_RULES_VERSION, '23.13.80');
assert.equal(version.ENGINE_PROTOCOL_VERSION, 'mp-23.19.2');

const constants = read(new URL('../../functions/src/shared/constants.js', import.meta.url));
const config = read(new URL('../../functions/src/economy/config.js', import.meta.url));
const index = read(new URL('../../functions/src/index.js', import.meta.url));
const impl = read(new URL('../js/firebaseClientImpl.js', import.meta.url));
const ui = read(new URL('../js/ui.js', import.meta.url));
const clientFacade = read(new URL('../js/firebaseClient.js', import.meta.url));
const manifest = JSON.parse(read(new URL('../build-manifest.json', import.meta.url)));

assert.match(constants, /mode: ECONOMY_MODES\.SERVER_REQUIRED/);
assert.match(constants, /minInstances: 0/);
assert.match(constants, /maxInstances: 1/);
assert.match(constants, /concurrency: 10/);
assert.match(constants, /enforceAppCheck: false/);
assert.match(config, /mode: ECONOMY_MODES\.SERVER_REQUIRED/);
assert.match(config, /minimumEconomyClientVersion: ECONOMY_PROTOCOL_VERSION/);
assert.match(index, /browserEconomyWrites: 'denied_by_rules_23\.13\.80'/);
assert.match(index, /authorityCutover: 'server_required'/);
assert.match(impl, /mode: 'server_required'/);
assert.match(impl, /server_required fail-closed/);
assert.match(impl, /server_owned_game_result/);
assert.match(impl, /ECONOMY_SERVER_AUTHORITY_REQUIRED/);
assert.match(impl, /function economyShouldUseServer\(_config\) \{ return true; \}/);
assert.doesNotMatch(impl, /async function trackPlayerStats\(/);
assert.doesNotMatch(impl, /async function settleSoloGameRewardOnce\(/);
assert.doesNotMatch(impl, /async function settlePvpGameRewardOnce\(/);
const createProfileBlock = impl.slice(impl.indexOf('export async function createUserProfile'), impl.indexOf('export function touchLastSeen'));
assert.match(createProfileBlock, /completeStarterDeckServer/);
assert.doesNotMatch(createProfileBlock, /runTransaction\(|tx\.set\(|tx\.update\(/);
const saveConfigBlock = impl.slice(impl.indexOf('export async function saveAdminGameConfigDocument'), impl.indexOf('// Wrappers históricos'));
assert.match(saveConfigBlock, /id === 'economy'/);
assert.match(saveConfigBlock, /ECONOMY_SERVER_AUTHORITY_REQUIRED/);
assert.doesNotMatch(impl.slice(impl.indexOf('export async function bootstrapPlayerStatistics'), impl.indexOf('export async function fetchPublicPlayerStats')), /runTransaction\(/);
assert.doesNotMatch(impl.slice(impl.indexOf('export async function recordPlayerGameResult'), impl.indexOf('export async function fetchPublicPlayerStats')), /trackPlayerStats\(/);

assert.match(impl, /export async function fetchEconomyAuditForAdmin/);
assert.match(impl, /collection\(db, 'economyEvents'\)/);
assert.match(impl, /collection\(db, 'adminActions'\)/);
assert.match(clientFacade, /fetchEconomyAuditForAdmin/);
assert.match(ui, /data-admin-pane="economyAudit"/);
assert.match(ui, /ECONOMÍA \/ AUDITORÍA|admin\.tab\.economyAudit/);
assert.match(ui, /admin-economy-audit-export/);
assert.match(ui, /operationId/);

assert.equal(manifest.engineVersion, '23.20.0');
assert.equal(manifest.economyProtocolVersion, 'econ-23.19.5.6');
assert.equal(manifest.economySchemaVersion, 8);
assert.equal(manifest.firestoreRulesVersion, '23.13.80');
console.log('ECONOMY_WRITE_FIREWALL_CUTOVER_23_19_5_6_OK mode=SERVER_REQUIRED rules=23.13.80 browserEconomyWrites=DENY stats=SERVER receipts=SERVER audit=IMMUTABLE+ADMIN_VIEWER costSafety=0/1/10 appCheck=OBSERVE_ONLY');
