import fs from 'node:fs';
import assert from 'node:assert/strict';
const ui=fs.readFileSync(new URL('../js/ui.js',import.meta.url),'utf8');
const texts=fs.readFileSync(new URL('../js/gameTexts.js',import.meta.url),'utf8');
const core=fs.readFileSync(new URL('../../functions/src/economy/tradeCore.js',import.meta.url),'utf8');
assert.match(ui,/const publishFilters=\{query:'',colors:new Set\(\),rarity:'',type:''\}/);
assert.match(ui,/renderPublishFilters\(\)/);
assert.match(ui,/trade-publish-browser/);
assert.match(ui,/renderPublishFilters\(\)\{return renderTradeFilterToolbar\(publishFilters,'trade-publish'\);\}/);
assert.match(ui,/root\.querySelector\('#trade-publish-search'\)/);
assert.match(ui,/root\.querySelector\('#trade-publish-filter-rarity'\)/);
assert.match(ui,/root\.querySelector\('#trade-publish-filter-type'\)/);
assert.match(ui,/data-criterion-card-search=/);
assert.doesNotMatch(ui,/list="trade-all-card-names"/);
assert.match(ui,/data-criterion-card-suggestions=/);
assert.match(ui,/tradeFindCardsByNameQuery/);
assert.doesNotMatch(ui,/data-criterion-card="\$\{i\}">\$\{tradeAllCardOptions/);
assert.match(ui,/data-criterion-card-type=/);
assert.match(ui,/wantedCriteria\.push\(\{type:'attributes',cardType,color,rarity\}\)/);
assert.match(texts,/Tipo \+ Color \+ Rareza/);
assert.match(core,/TRADE_CARD_TYPES/);
assert.match(core,/criterion\.cardType && !tradeCardTypeKeys\(card\)\.includes\(criterion\.cardType\)/);
console.log('TRADE_MARKET_REOPEN_23_21_3_OK publishFilters=EXPLORE_PARITY exactCard=INCREMENTAL_SEARCHBOX attributes=TYPE_COLOR_RARITY server=AUTHORITATIVE');
