import { HttpsError } from 'firebase-functions/v2/https';

const MAP = Object.freeze({
  AUTH_REQUIRED: ['unauthenticated', 'Tenés que iniciar sesión.'],
  INVALID_OPERATION_ID: ['invalid-argument', 'operationId inválido.'],
  OPERATION_ID_PAYLOAD_MISMATCH: ['failed-precondition', 'Ese operationId ya fue usado con otro payload.'],
  ECONOMY_DISABLED: ['unavailable', 'La economía está temporalmente pausada.'],
  ECONOMY_CLIENT_TOO_OLD: ['failed-precondition', 'Actualizá Argentinia para usar esta operación económica.'],
  INVALID_ECONOMY_REQUEST: ['invalid-argument', 'Solicitud económica inválida.'],
  RATE_LIMITED: ['resource-exhausted', 'Demasiadas operaciones económicas. Esperá un momento e intentá de nuevo.'],
  USERNAME_TAKEN: ['already-exists', 'Ese nombre ya está usado.'],
  USERNAME_ALREADY_CONFIGURED: ['failed-precondition', 'La cuenta ya tiene un nombre configurado.'],
  USERNAME_REQUIRED: ['failed-precondition', 'Primero elegí tu nombre en Argentinia.'],
  USERNAME_LENGTH: ['invalid-argument', 'Usá entre 3 y 18 caracteres.'],
  USERNAME_CHARS: ['invalid-argument', 'Usá letras, números, espacios o guion bajo.'],
  USERNAME_KEY_LENGTH: ['invalid-argument', 'El nombre debe tener al menos 3 caracteres visibles.'],
  USERNAME_RESERVED: ['invalid-argument', 'Ese nombre está reservado por Argentinia.'],
  USERNAME_BLOCKED: ['invalid-argument', 'Ese nombre no está permitido.'],
  STARTER_IDENTITY_INVALID: ['invalid-argument', 'Elegí uno o dos colores válidos para el mazo inicial.'],
  STARTER_ALREADY_COMPLETED: ['failed-precondition', 'El mazo inicial ya fue asignado.'],
  STARTER_PROFILE_MISSING: ['failed-precondition', 'La cuenta todavía no está inicializada.'],
  STARTER_POOL_INVALID: ['internal', 'El pool trusted del servidor no pudo construir un starter válido.'],
  PROFILE_MISSING: ['failed-precondition', 'No se encontró tu perfil.'],
  CAMPAIGN_POLICY_UNAVAILABLE: ['unavailable', 'No se pudo validar la política de campañas. Probá de nuevo.'],
  STORE_INSUFFICIENT_POINTS: ['failed-precondition', 'No te alcanzan los puntos para este sobre.'],
  CRAFT_CARD_NOT_ELIGIBLE: ['invalid-argument', 'Por ahora sólo se pueden mejorar Criaturas.'],
  CRAFT_KEYWORD_INVALID: ['invalid-argument', 'Esa mejora no está habilitada.'],
  CRAFT_CARD_NOT_OWNED: ['failed-precondition', 'No tenés esa carta en tu colección.'],
  CRAFT_ALREADY_ENHANCED: ['failed-precondition', 'Esa carta ya tiene una mejora.'],
  CRAFT_INSUFFICIENT_FICHAS: ['failed-precondition', 'No te alcanzan las Fichas.'],
  PREBUILT_NOT_FOUND: ['not-found', 'Ese mazo prearmado no existe.'],
  PREBUILT_NAME_REQUIRED: ['invalid-argument', 'Elegí un nombre para el mazo.'],
  PREBUILT_NAME_TOO_LONG: ['invalid-argument', 'El nombre del mazo no puede tener más de 30 caracteres.'],
  PREBUILT_DECK_LIMIT: ['failed-precondition', 'Ya alcanzaste el máximo de mazos guardados.'],
  PREBUILT_ALREADY_PURCHASED: ['failed-precondition', 'Ese mazo prearmado ya fue comprado por esta cuenta.'],
  PREBUILT_INSUFFICIENT_FUNDS: ['failed-precondition', 'No te alcanzan los puntos o las Fichas.'],
  CLASSIFIEDS_WEEK_NOT_PUBLISHED: ['failed-precondition', 'Los Avisos Clasificados de esta semana todavía no fueron publicados.'],
  CLASSIFIEDS_SCHEDULE_INVALID: ['internal', 'La publicación de Avisos Clasificados no supera su contrato trusted.'],
  CLASSIFIEDS_CARD_NOT_OFFERED: ['failed-precondition', 'Esa carta no forma parte de los Avisos Clasificados de esta semana.'],
  CLASSIFIEDS_ALREADY_PURCHASED: ['failed-precondition', 'Esa carta ya la compraste esta semana.'],
  CLASSIFIEDS_INSUFFICIENT_FUNDS: ['failed-precondition', 'No te alcanzan los puntos o las Fichas para comprar esta carta.'],
  CLASSIFIEDS_SLOT_LIMIT_REACHED: ['failed-precondition', 'Ya alcanzaste el cupo semanal para esa rareza.'],
  USERNAME_ACTIVE_MATCH: ['failed-precondition', 'Terminá tu partida multiplayer antes de cambiar el nombre.'],
  USERNAME_SAME: ['failed-precondition', 'Ese ya es tu nombre actual.'],
  USERNAME_NOT_ENOUGH_FICHAS: ['failed-precondition', 'No tenés suficientes Fichas.'],
  USERNAME_REGISTRY_MISMATCH: ['failed-precondition', 'La reserva del nombre actual está inconsistente.'],
  ADMIN_REQUIRED: ['permission-denied', 'Esta operación es exclusiva del admin.'],
  REGISTRATION_PAUSED: ['resource-exhausted', 'El registro de nuevos jugadores está temporalmente pausado.'],
  REGISTRATION_CAPACITY_REACHED: ['resource-exhausted', 'Argentinia alcanzó temporalmente su cupo de nuevos jugadores.'],
  REGISTRATION_DAILY_LIMIT_REACHED: ['resource-exhausted', 'Se alcanzó el cupo de altas de hoy. Probá nuevamente más adelante.'],
  REGISTRATION_UNAVAILABLE: ['unavailable', 'No se pudo validar el cupo de nuevos jugadores. Probá de nuevo.'],
  MATCH_REWARD_INVALID: ['invalid-argument', 'Solicitud de premio de partida inválida.'],
  MATCH_REWARD_DIFFICULTY_REQUIRED: ['invalid-argument', 'Falta la dificultad de la partida contra el Tano.'],
  MATCH_REWARD_MATCH_REQUIRED: ['invalid-argument', 'Falta el identificador de la partida multiplayer.'],
  PVP_MATCH_NOT_FOUND: ['not-found', 'No se encontró la partida multiplayer.'],
  PVP_NOT_MATCH_PARTICIPANT: ['permission-denied', 'Tu cuenta no participa de esa partida.'],
  PVP_MATCH_NOT_TERMINAL: ['failed-precondition', 'La partida todavía no tiene evidencia terminal válida.'],
  PVP_MATCH_NOT_READY: ['failed-precondition', 'La partida no llegó al estado ready requerido para liquidar premios.'],
  PVP_MATCH_NOT_SEALED: ['failed-precondition', 'La partida todavía no fue sellada por el servidor.'],
  PVP_TERMINAL_EVIDENCE_MISMATCH: ['failed-precondition', 'La evidencia terminal de la partida es inconsistente.'],
  PVP_OUTCOME_MISMATCH: ['failed-precondition', 'El resultado solicitado no coincide con la evidencia del servidor.'],
  PVP_ABANDON_EVIDENCE_MISMATCH: ['failed-precondition', 'La penalidad de abandono no coincide con la evidencia del servidor.'],
  ABANDON_MODE_INVALID: ['invalid-argument', 'Modo de abandono inválido.'],
  ABANDON_RECEIPT_REQUIRED: ['invalid-argument', 'Falta el identificador durable del abandono.'],
  ABANDON_RECEIPT_CONFLICT: ['failed-precondition', 'La partida ya tiene una liquidación incompatible con un abandono.'],
  ADMIN_REWARD_REPAIR_ABANDONED: ['failed-precondition', 'Una partida abandonada no puede repararse como premio positivo.'],
  DAILY_REWARD_INVALID: ['invalid-argument', 'Ese premio diario no existe.'],
  DAILY_LOGIN_REQUIRED: ['failed-precondition', 'Volvé a entrar para sincronizar tu recompensa diaria con el servidor.'],
  DAILY_REWARD_NOT_AVAILABLE: ['failed-precondition', 'Ese premio no está disponible o ya fue reclamado.'],
  DAILY_DEBUG_MODE_INVALID: ['invalid-argument', 'Modo de debug diario inválido.'],
  DAILY_DEBUG_MAX: ['failed-precondition', 'El reloj QA ya está en el máximo de +30 días.'],
  TOURNAMENT_NOT_FOUND: ['not-found', 'No se encontró el torneo.'],
  TOURNAMENT_NOT_ACTIVE: ['failed-precondition', 'Ese torneo ya terminó.'],
  TOURNAMENT_MATCH_NOT_ACTIVE: ['failed-precondition', 'Esa partida de torneo no está activa.'],
  TOURNAMENT_BRACKET_INVALID: ['internal', 'El fixture del torneo es inconsistente.'],
  TOURNAMENT_RECEIPT_CONFLICT: ['failed-precondition', 'La partida de torneo ya tiene un resultado incompatible.'],
  INTERNAL: ['internal', 'Error interno de Economy Authority.']
});

export function economyError(code, details = undefined, overrideMessage = undefined) {
  const [httpsCode, defaultMessage] = MAP[code] || MAP.INTERNAL;
  const error = new HttpsError(httpsCode, overrideMessage || defaultMessage, { code, ...(details || {}) });
  error.argentiniaCode = code;
  return error;
}

export function errorCode(error) {
  return error?.argentiniaCode || error?.details?.code || error?.code || 'INTERNAL';
}
