// Flasheras Stage27 — browser mirror of the physical ownership + Admin config contract.
import { cardVariantId, parseCardVariantId, stateVariantId } from './cardVariant.js';
export const FLASHERA_SCHEMA_VERSION=1;
export const FLASHERA_PROFILE_FIELD='flasheraCopies';
export const FLASHERA_ROLL_ALGORITHM='flashera-v1';
export const DEFAULT_FLASHERA_SETTINGS=Object.freeze({schemaVersion:1,acquisitionEnabled:false,visualEnabled:true,packChanceBps:3333,evolutionChanceBps:800,mixerChanceBps:1000,sanctuaryChanceBps:500});
const nonneg=value=>Math.max(0,Math.floor(Number(value)||0));
const clampBps=(value,fallback)=>Math.max(0,Math.min(10000,Number.isFinite(Number(value))?Math.round(Number(value)):fallback));
export function normalizeFlasheraSettings(raw={}){const source=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};return Object.freeze({schemaVersion:1,acquisitionEnabled:typeof source.acquisitionEnabled==='boolean'?source.acquisitionEnabled:false,visualEnabled:typeof source.visualEnabled==='boolean'?source.visualEnabled:true,packChanceBps:clampBps(source.packChanceBps,3333),evolutionChanceBps:clampBps(source.evolutionChanceBps,800),mixerChanceBps:clampBps(source.mixerChanceBps,1000),sanctuaryChanceBps:clampBps(source.sanctuaryChanceBps,500)});}
export function normalizeFlasheraCopies(raw={}){const source=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};const out={};for(const [rawKey,rawCount] of Object.entries(source)){const parsed=parseCardVariantId(rawKey),count=nonneg(rawCount);if(!parsed.valid||parsed.flashera||count<1)continue;const key=stateVariantId(parsed.canonicalId);if(key)out[key]=Math.max(out[key]||0,count);}return out;}
function ownedCount(collection=[],baseId=''){return(Array.isArray(collection)?collection:[]).reduce((total,raw)=>total+(String(raw)===baseId?1:0),0);}
function hasEnhancement(profile={},baseId=''){return!!(profile?.enhancements&&typeof profile.enhancements==='object'&&!Array.isArray(profile.enhancements)&&profile.enhancements[baseId]);}
function evolutionStage(profile={},baseId=''){const row=profile?.evolutions&&typeof profile.evolutions==='object'&&!Array.isArray(profile.evolutions)?profile.evolutions[baseId]:null;return Math.max(0,Math.min(2,Math.floor(Number(row?.stage??row)||0)));}
export function physicalStateCapacity(profile={},rawStateId=''){const parsed=parseCardVariantId(rawStateId);if(!parsed.valid||parsed.flashera)return 0;const count=ownedCount(profile?.collection,parsed.baseId);if(count<1)return 0;const enhanced=hasEnhancement(profile,parsed.baseId),evo=evolutionStage(profile,parsed.baseId);if(parsed.state==='enhanced')return enhanced?1:0;if(parsed.state==='evo1')return evo===1?1:0;if(parsed.state==='evo2')return evo===2?1:0;return Math.max(0,count-(enhanced?1:0)-(evo>0?1:0));}
export function reconcileFlasheraCopies(profile={},overrideCopies=undefined){const source=normalizeFlasheraCopies(overrideCopies===undefined?profile?.[FLASHERA_PROFILE_FIELD]:overrideCopies);const out={};for(const [stateId,count] of Object.entries(source)){const kept=Math.min(physicalStateCapacity(profile,stateId),nonneg(count));if(kept>0)out[stateId]=kept;}return out;}
export function flasheraCountForState(profile={},rawStateId=''){const stateId=stateVariantId(rawStateId);if(!stateId)return 0;const copies=reconcileFlasheraCopies(profile);return Math.min(physicalStateCapacity(profile,stateId),nonneg(copies[stateId]));}
export function availableCopiesForVariant(profile={},rawVariantId=''){const parsed=parseCardVariantId(rawVariantId);if(!parsed.valid)return 0;const stateId=cardVariantId(parsed.baseId,{state:parsed.state,flashera:false});const capacity=physicalStateCapacity(profile,stateId),flash=flasheraCountForState(profile,stateId);return parsed.flashera?flash:Math.max(0,capacity-flash);}
