import {
  adminGetNotificationCenter, adminSaveNotificationSettings, adminSaveNotificationRecipient,
  adminDeleteNotificationRecipient, adminSaveNotificationEvent, adminSaveNotificationTemplate,
  adminRestoreNotificationTemplate, adminRestoreNotificationTemplateVersion, adminSendNotificationTest, adminRetryNotification
} from './firebaseClient.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=ms=>ms?new Date(Number(ms)).toLocaleString('es-AR'):'—';
const demoVars={username:'Jugador de prueba',subject:'Prueba del Centro de Notificaciones',kind:'contact',caseId:'CASE-TEST-001',tradeId:'TRADE-TEST',status:'champion',roundKey:'final',pointsGain:'100',packsGain:'1',targetUid:'TEST_UID',receiptId:'TEST_RECEIPT',errorCode:'TEST_ERROR',adminUrl:'https://magiayleyenda.com.ar/',appUrl:'https://magiayleyenda.com.ar/'};
function renderTokens(s){return String(s||'').replace(/{{\s*([A-Za-z0-9_]+)\s*}}/g,(_,k)=>esc(demoVars[k]??''));}
function css(){return `<style>
.notifications-admin{max-width:1280px;margin:0 auto}.notif-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}.notif-card{background:#101b14;border:1px solid #52634e;border-radius:12px;padding:16px;margin-bottom:14px}.notif-card h3{margin:0 0 10px;color:#dbc776}.notif-row{display:grid;grid-template-columns:minmax(160px,.8fr) minmax(220px,1.4fr);gap:10px;align-items:center;margin:8px 0}.notif-input,.notif-select,.notif-textarea{width:100%;box-sizing:border-box;background:#07100b;color:#efe4bc;border:1px solid #596b55;border-radius:8px;padding:9px}.notif-textarea{min-height:170px;font-family:ui-monospace,monospace;resize:vertical}.notif-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.notif-btn{border:1px solid #88783a;background:#2a2917;color:#f0df9b;border-radius:8px;padding:8px 12px;font-weight:700;cursor:pointer}.notif-btn:disabled{opacity:.45;cursor:wait}.notif-table{width:100%;border-collapse:collapse;font-size:12px}.notif-table th,.notif-table td{border-bottom:1px solid #314033;padding:8px;text-align:left;vertical-align:top}.notif-muted{color:#abae9e;font-size:12px}.notif-ok{color:#93d99c}.notif-bad{color:#ff9e9e}.notif-pill{display:inline-block;padding:2px 7px;border-radius:999px;background:#27372b;font-size:11px}.notif-preview{width:100%;height:440px;border:1px solid #596b55;border-radius:8px;background:white}.notif-scroll{overflow:auto;max-height:440px}.notif-event{display:grid;grid-template-columns:34px minmax(210px,1fr) 95px minmax(150px,.7fr) minmax(160px,.7fr);gap:8px;align-items:center;padding:8px;border-bottom:1px solid #28372b}.notif-status{min-height:18px;margin-top:8px;font-size:12px}@media(max-width:800px){.notif-row{grid-template-columns:1fr}.notif-event{grid-template-columns:32px 1fr}.notif-event>*:nth-child(n+3){grid-column:2}.notif-preview{height:340px}}
</style>`;}

export function mountAdminNotificationsPane(root){
  let snapshot=null,selectedTemplate='moderation_new_case';
  const setStatus=(msg,bad=false)=>{const el=root.querySelector('#notif-status');if(el){el.textContent=msg;el.className=`notif-status ${bad?'notif-bad':'notif-ok'}`;}};
  const busy=async(btn,fn)=>{if(btn)btn.disabled=true;try{return await fn();}finally{if(btn)btn.disabled=false;}};
  async function load(){root.innerHTML=`${css()}<div class="notifications-admin"><div class="notif-card">Cargando Centro de Notificaciones…</div></div>`;try{snapshot=await adminGetNotificationCenter();render();}catch(e){root.innerHTML=`${css()}<div class="notif-card notif-bad">No se pudo cargar Notificaciones: ${esc(e?.message||e)}</div>`;}}
  function render(){
    const s=snapshot?.settings||{},rec=snapshot?.recipients||[],events=snapshot?.events||[],templates=snapshot?.templates||[],versions=snapshot?.templateVersions||[],hist=snapshot?.history||[];if(!templates.some(t=>t.templateId===selectedTemplate))selectedTemplate=templates[0]?.templateId||'';const tpl=templates.find(t=>t.templateId===selectedTemplate)||{};
    root.innerHTML=`${css()}<div class="notifications-admin">
      <div class="notif-card"><h3>🔔 Sistema de notificaciones</h3><div class="notif-muted">El envío es server-side. Ninguna credencial SMTP llega al navegador. Las notificaciones a jugadores están preparadas en el schema pero bloqueadas en HF3.</div>
        <div class="notif-row"><label>Master switch</label><label><input id="notif-enabled" type="checkbox" ${s.enabled?'checked':''}> SISTEMA ACTIVO</label></div>
        <div class="notif-row"><label>Nombre del remitente</label><input id="notif-brand" class="notif-input" value="${esc(s.brandName)}"></div>
        <div class="notif-row"><label>Reply-To</label><input id="notif-reply" class="notif-input" value="${esc(s.replyTo)}"></div>
        <div class="notif-row"><label>URL del logo</label><input id="notif-logo" class="notif-input" value="${esc(s.logoUrl)}" placeholder="https://…/logo.png"></div>
        <div class="notif-row"><label>Retención historial (días)</label><input id="notif-retention" class="notif-input" type="number" min="7" max="180" value="${Number(s.retentionDays)||30}"></div>
        <div class="notif-row"><label>Firma HTML</label><textarea id="notif-signature" class="notif-textarea" style="min-height:90px">${esc(s.signatureHtml)}</textarea></div>
        <div class="notif-row"><label>Layout HTML global</label><textarea id="notif-layout" class="notif-textarea">${esc(s.layoutHtml)}</textarea></div>
        <div class="notif-actions"><button class="notif-btn" id="notif-save-settings">💾 Guardar configuración</button></div>
      </div>
      <div class="notif-grid"><div class="notif-card"><h3>📬 Destinatarios internos</h3><div class="notif-scroll"><table class="notif-table"><thead><tr><th>Email</th><th>Nombre</th><th>Grupos</th><th></th></tr></thead><tbody>${rec.map(r=>`<tr><td>${esc(r.email)}${r.enabled?'':' <span class="notif-pill">OFF</span>'}</td><td>${esc(r.name)}</td><td>${esc((r.groups||[]).join(', '))}</td><td><button class="notif-btn" data-rec-edit="${esc(r.id)}">Editar</button> <button class="notif-btn" data-rec-delete="${esc(r.id)}">✕</button></td></tr>`).join('')}</tbody></table></div><hr style="border-color:#314033"><input type="hidden" id="notif-rec-id"><div class="notif-row"><label>Email</label><input id="notif-rec-email" class="notif-input"></div><div class="notif-row"><label>Nombre</label><input id="notif-rec-name" class="notif-input"></div><div class="notif-row"><label>Grupos</label><input id="notif-rec-groups" class="notif-input" value="administrators"></div><label><input id="notif-rec-enabled" type="checkbox" checked> Activo</label><div class="notif-actions"><button class="notif-btn" id="notif-rec-save">Guardar destinatario</button><button class="notif-btn" id="notif-rec-clear">Nuevo</button></div></div>
      <div class="notif-card"><h3>🧪 SMTP / prueba</h3><div class="notif-muted">HF3 usa el secreto Firebase <code>NOTIFICATION_SMTP_JSON</code>. El ZIP incluye un helper seguro para configurarlo con Gmail/App Password. El master switch puede permanecer apagado mientras probás.</div><div class="notif-row"><label>Email de prueba</label><input id="notif-test-email" class="notif-input" value="magiayleyenda@gmail.com"></div><div class="notif-row"><label>Plantilla</label><select id="notif-test-template" class="notif-select">${templates.map(t=>`<option value="${esc(t.templateId)}">${esc(t.label)}</option>`).join('')}</select></div><div class="notif-actions"><button class="notif-btn" id="notif-test-send">Enviar email de prueba</button></div><div class="notif-muted" style="margin-top:12px">El test se encola aun con el master switch apagado. Si SMTP no está configurado quedará como FAILED en Historial.</div></div></div>
      <div class="notif-card"><h3>⚡ Eventos</h3><div class="notif-muted">Cada evento puede activarse/desactivarse y elegir su plantilla. Los avisos administrativos conectados en HF3 son Moderación, disputas, fin de torneo y fallos de reparación económica.</div><div>${events.map(e=>`<div class="notif-event" data-event="${esc(e.eventId)}"><input type="checkbox" data-f="enabled" ${e.enabled?'checked':''}><div><strong>${esc(e.label)}</strong><div class="notif-muted">${esc(e.eventId)}</div></div><span class="notif-pill">${esc(e.severity)}</span><select class="notif-select" data-f="templateId">${templates.map(t=>`<option value="${esc(t.templateId)}" ${t.templateId===e.templateId?'selected':''}>${esc(t.label)}</option>`).join('')}</select><input class="notif-input" data-f="groups" value="${esc((e.audienceGroups||[]).join(','))}" title="Grupos destinatarios separados por coma"></div>`).join('')}</div><div class="notif-actions"><button class="notif-btn" id="notif-save-events">💾 Guardar eventos</button></div></div>
      <div class="notif-card"><h3>✉️ Plantillas</h3><div class="notif-row"><label>Plantilla</label><select id="notif-template-select" class="notif-select">${templates.map(t=>`<option value="${esc(t.templateId)}" ${t.templateId===selectedTemplate?'selected':''}>${esc(t.label)} · v${Number(t.version)||1}</option>`).join('')}</select></div><div class="notif-row"><label>Versiones guardadas</label><select id="notif-template-version" class="notif-select"><option value="">— seleccionar versión anterior —</option>${versions.filter(v=>v.templateId===selectedTemplate).map(v=>`<option value="${esc(v.versionId)}">v${Number(v.version)||1} · ${esc(dt(v.createdAtMs))}</option>`).join('')}</select></div><div class="notif-row"><label>Asunto</label><input id="notif-template-subject" class="notif-input" value="${esc(tpl.subject)}"></div><div class="notif-row"><label>Preheader</label><input id="notif-template-preheader" class="notif-input" value="${esc(tpl.preheader)}"></div><label>HTML</label><textarea id="notif-template-html" class="notif-textarea">${esc(tpl.html)}</textarea><label>Texto plano</label><textarea id="notif-template-text" class="notif-textarea" style="min-height:100px">${esc(tpl.text)}</textarea><div class="notif-muted">Variables: {{username}}, {{subject}}, {{caseId}}, {{kind}}, {{tradeId}}, {{status}}, {{roundKey}}, {{pointsGain}}, {{packsGain}}, {{targetUid}}, {{receiptId}}, {{errorCode}}, {{adminUrl}}, {{appUrl}}.</div><div class="notif-actions"><button class="notif-btn" id="notif-template-save">💾 Guardar versión</button><button class="notif-btn" id="notif-template-preview">Vista previa</button><button class="notif-btn" id="notif-template-restore-version">Restaurar versión seleccionada</button><button class="notif-btn" id="notif-template-restore">Restaurar predeterminada</button></div><iframe id="notif-preview" class="notif-preview" sandbox="" style="display:none"></iframe></div>
      <div class="notif-card"><h3>🧾 Historial de envíos</h3><div class="notif-actions"><button class="notif-btn" id="notif-refresh">🔄 Actualizar</button></div><div class="notif-scroll"><table class="notif-table"><thead><tr><th>Fecha</th><th>Evento</th><th>Estado</th><th>Destinatarios</th><th>Intentos</th><th>Error</th><th></th></tr></thead><tbody>${hist.length?hist.map(h=>`<tr><td>${esc(dt(h.createdAtMs))}</td><td>${esc(h.eventId)}${h.isTest?' <span class="notif-pill">TEST</span>':''}</td><td><span class="notif-pill">${esc(h.status)}</span></td><td>${esc((h.recipients||[]).join(', ')||'—')}</td><td>${Number(h.attempts)||0}</td><td>${esc(h.lastError||'')}</td><td>${['failed','suppressed'].includes(h.status)?`<button class="notif-btn" data-retry="${esc(h.notificationId)}">Reintentar</button>`:''}</td></tr>`).join(''):`<tr><td colspan="7">Sin envíos todavía.</td></tr>`}</tbody></table></div></div>
      <div class="notif-card"><h3>👤 Próxima etapa · jugadores</h3><div class="notif-muted">Schema preparado para audiencia por UID y preferencias, pero <strong>playerEmailEnabled está bloqueado en false en HF3</strong>. La futura etapa agregará emails verificados, categorías transaccional/opcional y unsubscribe antes de habilitar cualquier envío masivo.</div></div>
      <div id="notif-status" class="notif-status"></div>
    </div>`;
    bind();
  }
  function bind(){
    root.querySelector('#notif-save-settings')?.addEventListener('click',async e=>{try{const btn=e.currentTarget;await busy(btn,()=>adminSaveNotificationSettings({enabled:root.querySelector('#notif-enabled').checked,brandName:root.querySelector('#notif-brand').value,replyTo:root.querySelector('#notif-reply').value,logoUrl:root.querySelector('#notif-logo').value,retentionDays:Number(root.querySelector('#notif-retention').value),signatureHtml:root.querySelector('#notif-signature').value,layoutHtml:root.querySelector('#notif-layout').value}));setStatus('Configuración guardada.');await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelectorAll('[data-rec-edit]').forEach(b=>b.addEventListener('click',()=>{const r=snapshot.recipients.find(x=>x.id===b.dataset.recEdit);if(!r)return;root.querySelector('#notif-rec-id').value=r.id;root.querySelector('#notif-rec-email').value=r.email;root.querySelector('#notif-rec-name').value=r.name;root.querySelector('#notif-rec-groups').value=(r.groups||[]).join(',');root.querySelector('#notif-rec-enabled').checked=r.enabled!==false;}));
    root.querySelectorAll('[data-rec-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('¿Eliminar este destinatario?'))return;try{await adminDeleteNotificationRecipient(b.dataset.recDelete);await load();}catch(err){setStatus(err?.message||String(err),true);}}));
    root.querySelector('#notif-rec-clear')?.addEventListener('click',()=>{root.querySelector('#notif-rec-id').value='';root.querySelector('#notif-rec-email').value='';root.querySelector('#notif-rec-name').value='';root.querySelector('#notif-rec-groups').value='administrators';root.querySelector('#notif-rec-enabled').checked=true;});
    root.querySelector('#notif-rec-save')?.addEventListener('click',async e=>{try{await busy(e.currentTarget,()=>adminSaveNotificationRecipient({id:root.querySelector('#notif-rec-id').value,email:root.querySelector('#notif-rec-email').value,name:root.querySelector('#notif-rec-name').value,groups:root.querySelector('#notif-rec-groups').value.split(',').map(v=>v.trim()).filter(Boolean),enabled:root.querySelector('#notif-rec-enabled').checked}));await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-save-events')?.addEventListener('click',async e=>{try{await busy(e.currentTarget,async()=>{for(const row of root.querySelectorAll('[data-event]'))await adminSaveNotificationEvent({eventId:row.dataset.event,enabled:row.querySelector('[data-f="enabled"]').checked,templateId:row.querySelector('[data-f="templateId"]').value,audienceGroups:row.querySelector('[data-f="groups"]').value.split(',').map(v=>v.trim()).filter(Boolean)});});setStatus('Eventos guardados.');await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-template-select')?.addEventListener('change',e=>{selectedTemplate=e.target.value;render();});
    root.querySelector('#notif-template-save')?.addEventListener('click',async e=>{try{await busy(e.currentTarget,()=>adminSaveNotificationTemplate({templateId:selectedTemplate,subject:root.querySelector('#notif-template-subject').value,preheader:root.querySelector('#notif-template-preheader').value,html:root.querySelector('#notif-template-html').value,text:root.querySelector('#notif-template-text').value}));setStatus('Nueva versión de plantilla guardada.');await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-template-restore-version')?.addEventListener('click',async e=>{const versionId=root.querySelector('#notif-template-version')?.value;if(!versionId){setStatus('Seleccioná una versión anterior.',true);return;}if(!confirm('¿Restaurar esta versión? Se guardará como una nueva versión.'))return;try{await busy(e.currentTarget,()=>adminRestoreNotificationTemplateVersion(selectedTemplate,versionId));await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-template-restore')?.addEventListener('click',async e=>{if(!confirm('¿Restaurar la plantilla predeterminada? Se guardará como una nueva versión.'))return;try{await busy(e.currentTarget,()=>adminRestoreNotificationTemplate(selectedTemplate));await load();}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-template-preview')?.addEventListener('click',()=>{const frame=root.querySelector('#notif-preview');const body=renderTokens(root.querySelector('#notif-template-html').value);const logo=root.querySelector('#notif-logo')?.value?`<img src="${esc(root.querySelector('#notif-logo').value)}" style="max-width:220px">`:`<h2>${esc(root.querySelector('#notif-brand')?.value||'Argentinia')}</h2>`;let layout=root.querySelector('#notif-layout')?.value||'{{logoBlock}}{{emailBody}}{{signatureHtml}}';layout=layout.replace(/{{\s*logoBlock\s*}}/g,logo).replace(/{{\s*emailBody\s*}}/g,body).replace(/{{\s*signatureHtml\s*}}/g,root.querySelector('#notif-signature')?.value||'');frame.srcdoc=layout;frame.style.display='block';});
    root.querySelector('#notif-test-send')?.addEventListener('click',async e=>{try{const out=await busy(e.currentTarget,()=>adminSendNotificationTest({email:root.querySelector('#notif-test-email').value,templateId:root.querySelector('#notif-test-template').value}));setStatus(`Email de prueba encolado${out?.notificationId?` (${out.notificationId})`:''}. Actualizá Historial para ver el resultado.`);}catch(err){setStatus(err?.message||String(err),true);}});
    root.querySelector('#notif-refresh')?.addEventListener('click',()=>load());root.querySelectorAll('[data-retry]').forEach(b=>b.addEventListener('click',async()=>{try{await adminRetryNotification(b.dataset.retry);await load();}catch(err){setStatus(err?.message||String(err),true);}}));
  }
  return {load};
}
