// HF23.3.16.1 — Perfil Público + vitrina de Carta Favorita + slots cosméticos futuros.
// @game-text-surface strict
import { fetchPublicPlayerProfile, setPublicProfileFavoriteCard } from './firebaseClient.js';
import { achievementTrophyPath, ACHIEVEMENT_TIER_ICONS } from './achievements.js';
import { POOL_BASELINE } from './poolContract.js';
import { formatDuration } from './statistics.js';
import { cardDb } from './cardLoader.js';
import { gameText } from './gameTexts.js';

const esc=value=>{const d=document.createElement('div');d.textContent=value==null?'':String(value);return d.innerHTML;};
const n=value=>Math.max(0,Math.floor(Number(value)||0));
const pct=(wins,games)=>games>0?Math.max(0,Math.min(100,(Number(wins)||0)*100/Number(games))):0;
const FAVORITE_ENHANCED_SUFFIX='::enhanced';
let host={getCurrentUid:()=>'',getOwnedCardIds:()=>[],getEnhancements:()=>({}),getEvolutions:()=>({}),renderCard:null,onFavoriteChanged:null};

export function configurePublicProfileUI(next={}){
  host={...host,...(next&&typeof next==='object'?next:{})};
}

function injectStyles(){
  if(document.getElementById('public-profile-styles')) return;
  const style=document.createElement('style');
  style.id='public-profile-styles';
  style.textContent=`
  #public-profile-overlay{position:fixed;inset:0;z-index:15050;background:radial-gradient(circle at 50% 0,#243024 0,#101710 38%,#080c09 100%);color:#e9dfc6;overflow:auto;padding:18px 22px 28px;box-sizing:border-box;overscroll-behavior:contain}
  .public-profile-shell{width:min(1180px,100%);margin:0 auto;display:flex;flex-direction:column;gap:16px}
  .public-profile-topbar{display:flex;align-items:center;gap:14px;position:sticky;top:0;z-index:3;padding:8px 0;background:linear-gradient(180deg,rgba(8,12,9,.98),rgba(8,12,9,.78),transparent)}
  .public-profile-back{border:1px solid #d4af37;background:rgba(12,20,14,.93);color:#f5df9b;border-radius:9px;padding:9px 15px;font-weight:900;cursor:pointer}
  .public-profile-kicker{text-transform:uppercase;letter-spacing:.16em;font-size:10px;color:#9f967e;font-weight:900}
  .public-profile-title{font:900 25px/1.1 Georgia,serif;color:#f6e6a7;text-shadow:0 0 18px rgba(212,175,55,.24)}
  .public-profile-hero{display:grid;grid-template-columns:auto 1fr;gap:22px;align-items:center;border:1px solid rgba(212,175,55,.45);border-radius:18px;padding:20px;background:linear-gradient(135deg,rgba(212,175,55,.09),rgba(255,255,255,.02) 42%,rgba(65,107,78,.08));box-shadow:0 18px 50px rgba(0,0,0,.3);position:relative;overflow:hidden}
  .public-profile-cosmetic-background-slot{position:absolute;inset:0;pointer-events:none;z-index:0}.public-profile-hero>*:not(.public-profile-cosmetic-background-slot){position:relative;z-index:1}
  .public-profile-avatar{width:112px;height:112px;border-radius:50%;object-fit:cover;border:3px solid #d4af37;background:#1b241c;box-shadow:0 0 24px rgba(212,175,55,.18)}
  .public-profile-avatar-fallback{display:flex;align-items:center;justify-content:center;font-size:54px}
  .public-profile-name-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.public-profile-name{font-size:30px;font-weight:950;color:#fff2bf;overflow-wrap:anywhere}.public-profile-name-badge-slot,.public-profile-title-slot{display:inline-flex;align-items:center;min-width:0}
  .public-profile-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:9px}.public-profile-pill{padding:6px 9px;border-radius:999px;background:rgba(0,0,0,.28);border:1px solid rgba(212,175,55,.22);font-size:11px;font-weight:850;color:#d8ceb1}
  .public-profile-section{border:1px solid rgba(212,175,55,.24);border-radius:14px;background:rgba(7,11,8,.62);padding:15px}.public-profile-section-title{font-size:15px;font-weight:950;color:#f0d98a;margin:0 0 12px;text-transform:uppercase;letter-spacing:.06em}
  .public-profile-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.public-profile-stat{min-width:0;border:1px solid rgba(255,255,255,.08);border-radius:10px;padding:11px;background:rgba(255,255,255,.025)}.public-profile-stat-label{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#968f7e;font-weight:900}.public-profile-stat-value{margin-top:4px;font-size:19px;color:#fff0b6;font-weight:950}.public-profile-stat-sub{margin-top:2px;font-size:10px;color:#aeb8af}
  .public-profile-favorite{display:grid;grid-template-columns:minmax(180px,260px) 1fr;gap:20px;align-items:center;background:radial-gradient(circle at 18% 50%,rgba(212,175,55,.12),transparent 36%),rgba(7,11,8,.72)}
  .public-profile-favorite-card{min-height:280px;display:flex;align-items:center;justify-content:center}.public-profile-favorite-card .card{--card-w:190px;filter:drop-shadow(0 16px 22px rgba(0,0,0,.42))}
  .public-profile-favorite-empty{width:180px;aspect-ratio:.716;border:2px dashed rgba(212,175,55,.32);border-radius:13px;display:flex;align-items:center;justify-content:center;text-align:center;padding:16px;box-sizing:border-box;color:#837d6d;font-size:12px}
  .public-profile-favorite-name{font-size:24px;font-weight:950;color:#fff0b6;margin-bottom:8px}.public-profile-favorite-copy{color:#aeb8af;font-size:12px;line-height:1.45}.public-profile-favorite-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.public-profile-favorite-btn{border:1px solid #d4af37;background:rgba(212,175,55,.12);color:#f5df9b;border-radius:9px;padding:8px 12px;font-weight:900;cursor:pointer}.public-profile-favorite-btn.secondary{border-color:#69756d;color:#bdc8bf;background:rgba(255,255,255,.035)}
  .public-profile-trophies{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.public-profile-achievement{border:1px solid rgba(212,175,55,.14);border-radius:12px;padding:10px;background:rgba(255,255,255,.02)}.public-profile-achievement-head{display:flex;justify-content:space-between;gap:8px;align-items:start}.public-profile-achievement-name{font-size:12px;font-weight:950;color:#ead99e}.public-profile-achievement-progress{font-size:11px;color:#a8b1a8;white-space:nowrap}.public-profile-tier-row{display:flex;gap:6px;margin-top:9px;align-items:center}.public-profile-trophy{width:48px;height:48px;border-radius:9px;display:flex;align-items:center;justify-content:center;position:relative;border:1px solid rgba(255,255,255,.08);background:rgba(0,0,0,.25)}.public-profile-trophy img{width:43px;height:43px;object-fit:contain}.public-profile-trophy.locked{filter:grayscale(1);opacity:.28}.public-profile-trophy.locked::after{content:'🔒';position:absolute;font-size:12px;right:1px;bottom:0}.public-profile-trophy-fallback{font-size:24px}.public-profile-trophy-label{display:none}
  .public-profile-loading,.public-profile-error{padding:60px 20px;text-align:center;color:#bcb49f}.public-profile-error{color:#efad9d}.public-profile-privacy{font-size:10px;color:#807b70;text-align:center;line-height:1.45}
  .public-profile-favorite-modal{position:fixed;inset:0;z-index:15150;background:rgba(0,0,0,.78);display:flex;align-items:center;justify-content:center;padding:18px}.public-profile-favorite-panel{width:min(760px,96vw);max-height:90vh;overflow:auto;border:2px solid #d4af37;border-radius:18px;background:linear-gradient(180deg,#172219,#08100b);padding:20px;box-sizing:border-box;box-shadow:0 24px 80px rgba(0,0,0,.7)}.public-profile-favorite-panel h3{margin:0;color:#f6e6a7;font-size:22px}.public-profile-favorite-picker{display:grid;grid-template-columns:1fr 250px;gap:16px;margin-top:14px}.public-profile-favorite-list-pane{min-width:0}.public-profile-favorite-list{width:100%;min-height:280px;background:#0c140e;color:#e9dfc6;border:1px solid #59645c;border-radius:9px;padding:6px}.public-profile-favorite-search{width:100%;box-sizing:border-box;margin-bottom:8px;padding:9px;border-radius:8px;border:1px solid #59645c;background:#0c140e;color:#fff}.public-profile-favorite-preview{display:flex;align-items:center;justify-content:center;min-height:300px;min-width:0;overflow:hidden}.public-profile-favorite-preview .card{--card-w:170px}.public-profile-favorite-modal-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:14px}
  @media(max-width:850px){#public-profile-overlay{padding:10px}.public-profile-hero{grid-template-columns:84px 1fr;gap:13px;padding:13px}.public-profile-avatar{width:80px;height:80px}.public-profile-name{font-size:23px}.public-profile-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.public-profile-trophies{grid-template-columns:1fr}.public-profile-trophy{width:42px;height:42px}.public-profile-trophy img{width:37px;height:37px}.public-profile-title{font-size:20px}.public-profile-favorite{grid-template-columns:150px 1fr;gap:12px}.public-profile-favorite-card{min-height:230px}.public-profile-favorite-card .card{--card-w:145px}.public-profile-favorite-empty{width:140px}.public-profile-favorite-modal{padding:6px;align-items:center}.public-profile-favorite-panel{width:min(98vw,820px);height:min(96dvh,610px);max-height:calc(100dvh - 12px);overflow:hidden;padding:12px;display:flex;flex-direction:column;gap:7px}.public-profile-favorite-panel h3{font-size:18px;line-height:1.05;flex:0 0 auto}.public-profile-favorite-panel>.public-profile-favorite-copy{font-size:10px;line-height:1.25;flex:0 0 auto}.public-profile-favorite-modal-actions{order:2;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%;gap:6px;margin:0;flex:0 0 auto}.public-profile-favorite-modal-actions .public-profile-favorite-btn{min-width:0;padding:7px 5px;font-size:11px;white-space:nowrap}.public-profile-favorite-picker{order:3;grid-template-columns:minmax(0,55%) minmax(0,45%);gap:8px;margin:0;min-height:0;flex:1;overflow:hidden;align-items:stretch}.public-profile-favorite-list-pane{display:flex;flex-direction:column;min-height:0;overflow:hidden}.public-profile-favorite-search{margin:0 0 6px;padding:7px;font-size:12px;flex:0 0 auto}.public-profile-favorite-list{min-height:0;height:100%;flex:1;font-size:12px;padding:4px;overflow-y:auto}.public-profile-favorite-preview{min-height:0;height:100%;align-self:stretch;overflow:hidden}.public-profile-favorite-preview .card{--card-w:min(27vw,calc((100dvh - 190px)*.70),175px);max-height:100%!important}.public-profile-favorite-panel>[data-fav-error]{order:4;min-height:14px!important;margin:0!important;flex:0 0 auto}}
  @media(max-width:480px){.public-profile-grid{grid-template-columns:1fr 1fr}.public-profile-hero{grid-template-columns:68px 1fr}.public-profile-avatar{width:64px;height:64px}.public-profile-name{font-size:19px}.public-profile-pill{font-size:9px}.public-profile-section{padding:11px}.public-profile-stat-value{font-size:16px}.public-profile-tier-row{gap:4px}.public-profile-trophy{width:38px;height:38px}.public-profile-trophy img{width:33px;height:33px}.public-profile-favorite{grid-template-columns:1fr;text-align:center}.public-profile-favorite-card{min-height:210px}.public-profile-favorite-actions{justify-content:center}.public-profile-favorite-name{font-size:20px}}
  `;
  document.head.appendChild(style);
}

function familyLabel(id){return gameText(`achievements.family.${id}`);}
function tierLabel(tier){return gameText(`achievements.tier.${tier}`);}
function trophyHtml(familyId,tier,unlocked){
  const icon=ACHIEVEMENT_TIER_ICONS[tier]||'🏆';
  if(!unlocked) return `<span class="public-profile-trophy locked" title="${esc(tierLabel(tier))}"><span class="public-profile-trophy-fallback">${icon}</span></span>`;
  return `<span class="public-profile-trophy" title="${esc(tierLabel(tier))}"><span class="public-profile-trophy-fallback">${icon}</span><img src="${esc(achievementTrophyPath(familyId,tier))}" alt="${esc(tierLabel(tier))}" onload="this.previousElementSibling.style.display='none'" onerror="this.style.display='none'"></span>`;
}
function stat(label,value,sub=''){return `<div class="public-profile-stat"><div class="public-profile-stat-label">${esc(label)}</div><div class="public-profile-stat-value">${esc(value)}</div>${sub?`<div class="public-profile-stat-sub">${esc(sub)}</div>`:''}</div>`;}
function formatJoined(ms){if(!ms)return '';try{return new Date(ms).toLocaleDateString('es-AR',{year:'numeric',month:'short'});}catch{return '';}}
function currentUid(){try{return String(host.getCurrentUid?.()||'');}catch{return '';}}
function ownedCardIds(){try{return Array.isArray(host.getOwnedCardIds?.())?host.getOwnedCardIds():[];}catch{return [];}}
function localEnhancements(){try{const value=host.getEnhancements?.();return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{return {};}}
function localEvolutions(){try{const value=host.getEvolutions?.();return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{return {};}}
function localEvolutionStage(baseId){const row=localEvolutions()[baseId];return Math.max(0,Math.min(2,Math.floor(Number(row?.stage??row)||0)));}
function parseFavoriteId(rawId){const id=String(rawId||'');return id.endsWith(FAVORITE_ENHANCED_SUFFIX)?{id,baseId:id.slice(0,-FAVORITE_ENHANCED_SUFFIX.length),variant:'enhanced'}:{id,baseId:id,variant:'base'};}
function enhancedDisplayCard(baseCard,keyword){const clean=String(keyword||'').trim();return clean?{...baseCard,keywords:[...new Set([...(baseCard.keywords||[]),clean])]}:baseCard;}
function favoriteDisplayName(cardId){const parsed=parseFavoriteId(cardId);const card=cardDb.getById(parsed.baseId);if(!card)return '';return parsed.variant==='enhanced'?gameText('publicProfile.favorite.enhancedName',{card:card.name||parsed.baseId}):String(card.name||parsed.baseId);}
function realOwnedCards(){
  const counts={}; for(const raw of ownedCardIds()){const id=String(raw||'');if(id)counts[id]=(counts[id]||0)+1;}
  const enhancements=localEnhancements(); const evolutions=localEvolutions(); const rows=[];
  for(const baseId of Object.keys(counts)){
    const card=cardDb.getById(baseId); if(!card||(typeof cardDb.isEnabled==='function'&&!cardDb.isEnabled(card.id)))continue;
    const enhancedKeyword=String(enhancements[baseId]||'').trim();
    const evoRow=evolutions[baseId]; const evoStage=Math.max(0,Math.min(2,Math.floor(Number(evoRow?.stage??evoRow)||0)));
    const special=(enhancedKeyword?1:0)+(evoStage>0?1:0);
    if(counts[baseId]>special) rows.push({favoriteId:baseId,baseId,card,displayCard:card,label:String(card.name||baseId)});
    if(enhancedKeyword&&counts[baseId]>=special) rows.push({favoriteId:`${baseId}${FAVORITE_ENHANCED_SUFFIX}`,baseId,card,displayCard:enhancedDisplayCard(card,enhancedKeyword),label:gameText('publicProfile.favorite.enhancedOption',{card:card.name||baseId,ability:enhancedKeyword})});
  }
  return rows.sort((a,b)=>String(a.label||'').localeCompare(String(b.label||''),'es-AR'));
}
function displayCardForFavorite(cardId,profile=null){
  const parsed=parseFavoriteId(cardId); const card=cardDb.getById(parsed.baseId); if(!card)return null;
  if(parsed.variant==='enhanced'){const keyword=String(profile?.favoriteCardEnhancementKeyword||localEnhancements()[parsed.baseId]||'').trim();return keyword?enhancedDisplayCard(card,keyword):null;}
  return card;
}
function renderRealCard(cardId,profile=null){
  const card=displayCardForFavorite(cardId,profile);
  if(!card) return null;
  try { const node=host.renderCard?.(card); if(node instanceof HTMLElement) return node; } catch(error){ console.warn('[PublicProfile] render favorite card fallback:',error); }
  const fallback=document.createElement('div');fallback.className='public-profile-favorite-empty';fallback.textContent=favoriteDisplayName(cardId)||String(card.name||card.id);return fallback;
}
function cosmeticAttr(profile,key){return esc(String(profile?.cosmetics?.[key]||''));}

function openFavoritePicker(profile,onSaved){
  document.querySelector('.public-profile-favorite-modal')?.remove();
  const cards=realOwnedCards();
  const modal=document.createElement('div');modal.className='public-profile-favorite-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');
  modal.innerHTML=`<div class="public-profile-favorite-panel"><h3>${esc(gameText('publicProfile.favorite.pickerTitle'))}</h3><div class="public-profile-favorite-copy">${esc(gameText('publicProfile.favorite.pickerHelp'))}</div><div class="public-profile-favorite-picker"><div class="public-profile-favorite-list-pane"><input class="public-profile-favorite-search" type="search" placeholder="${esc(gameText('publicProfile.favorite.search'))}"><select class="public-profile-favorite-list" size="12"></select></div><div class="public-profile-favorite-preview"></div></div><div class="public-profile-favorite-error" data-fav-error style="min-height:18px;color:#efad9d;font-size:11px;margin-top:10px;"></div><div class="public-profile-favorite-modal-actions"><button class="public-profile-favorite-btn secondary" data-fav-clear type="button">${esc(gameText('publicProfile.favorite.clear'))}</button><button class="public-profile-favorite-btn secondary" data-fav-cancel type="button">${esc(gameText('common.cancel'))}</button><button class="public-profile-favorite-btn" data-fav-save type="button">${esc(gameText('common.save'))}</button></div></div>`;
  document.body.appendChild(modal);
  const select=modal.querySelector('.public-profile-favorite-list');const search=modal.querySelector('.public-profile-favorite-search');const preview=modal.querySelector('.public-profile-favorite-preview');
  const refreshOptions=()=>{const q=String(search.value||'').trim().toLocaleLowerCase('es-AR');const filtered=cards.filter(row=>!q||String(row.label||'').toLocaleLowerCase('es-AR').includes(q));const previous=select.value||profile.favoriteCardId||'';select.innerHTML=filtered.map(row=>`<option value="${esc(row.favoriteId)}">${esc(row.label||row.favoriteId)}</option>`).join('');if(filtered.some(row=>row.favoriteId===previous))select.value=previous;else if(filtered[0])select.value=filtered[0].favoriteId;refreshPreview();};
  const refreshPreview=()=>{preview.replaceChildren();const selected=cards.find(row=>row.favoriteId===select.value);const cardNode=selected?(()=>{try{const node=host.renderCard?.(selected.displayCard);return node instanceof HTMLElement?node:null;}catch{return null;}})():null;if(cardNode)preview.appendChild(cardNode);else{const empty=document.createElement('div');empty.className='public-profile-favorite-empty';empty.textContent=gameText('publicProfile.favorite.noneOwned');preview.appendChild(empty);}};
  select.addEventListener('change',refreshPreview);search.addEventListener('input',refreshOptions);refreshOptions();
  const close=()=>modal.remove();modal.querySelector('[data-fav-cancel]')?.addEventListener('click',close);
  const persist=async cardId=>{const save=modal.querySelector('[data-fav-save]');const clear=modal.querySelector('[data-fav-clear]');const errorEl=modal.querySelector('[data-fav-error]');if(errorEl)errorEl.textContent='';save.disabled=true;clear.disabled=true;try{const out=await setPublicProfileFavoriteCard(cardId);const id=String(out?.favoriteCardId||'');host.onFavoriteChanged?.(id);close();onSaved?.(id);}catch(error){console.error('No se pudo actualizar Carta Favorita:',error);save.disabled=false;clear.disabled=false;if(errorEl)errorEl.textContent=gameText('publicProfile.favorite.error');}};
  modal.querySelector('[data-fav-save]')?.addEventListener('click',()=>{if(select.value)void persist(select.value);});
  modal.querySelector('[data-fav-clear]')?.addEventListener('click',()=>void persist(''));
}

export function showPublicPlayerProfile(targetUid,{onClose=null}={}){
  injectStyles();
  document.querySelector('#public-profile-overlay')?.remove();
  const overlay=document.createElement('div');overlay.id='public-profile-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');
  overlay.innerHTML=`<div class="public-profile-shell"><div class="public-profile-topbar"><button class="public-profile-back" type="button">← ${esc(gameText('common.back'))}</button><div><div class="public-profile-kicker">${esc(gameText('publicProfile.kicker'))}</div><div class="public-profile-title">${esc(gameText('publicProfile.title'))}</div></div></div><div class="public-profile-loading">${esc(gameText('publicProfile.loading'))}</div></div>`;
  document.body.appendChild(overlay);
  const close=()=>{document.removeEventListener('keydown',onKey);overlay.remove();onClose?.();};
  const onKey=e=>{if(e.key==='Escape'){e.preventDefault();close();}};document.addEventListener('keydown',onKey);overlay.querySelector('.public-profile-back')?.addEventListener('click',close);
  const renderProfile=profile=>{
    const s=profile.stats||{};const elo=n(s.eloRating)||1200;const eloGames=n(s.eloGames);const joined=formatJoined(profile.joinedAtMs);const wr=pct(s.wins,s.gamesPlayed);const isOwn=String(profile.uid||targetUid)===currentUid();
    const avatar=profile.photoURL?`<img class="public-profile-avatar" src="${esc(profile.photoURL)}" alt="" onerror="this.outerHTML='<div class=&quot;public-profile-avatar public-profile-avatar-fallback&quot;>🤠</div>'">`:`<div class="public-profile-avatar public-profile-avatar-fallback">🤠</div>`;
    const achievements=(Array.isArray(profile.achievements)?profile.achievements:[]).map(row=>{
      const tiers=Array.isArray(row.tiers)?row.tiers:[];
      const next=tiers.find(t=>t.enabled!==false&&!t.claimed);
      const progressTarget=next?.target||tiers.at(-1)?.target||0;
      return `<div class="public-profile-achievement"><div class="public-profile-achievement-head"><div class="public-profile-achievement-name">${esc(familyLabel(row.familyId))}</div><div class="public-profile-achievement-progress">${n(row.current).toLocaleString('es-AR')}${progressTarget?` / ${n(progressTarget).toLocaleString('es-AR')}`:''}</div></div><div class="public-profile-tier-row">${tiers.map(t=>trophyHtml(row.familyId,t.tier,!!t.claimed)).join('')}</div></div>`;
    }).join('');
    const favoriteId=String(profile.favoriteCardId||'');const favoriteName=String(profile.favoriteCardName||favoriteDisplayName(favoriteId)||'')+(favoriteId&&profile.favoriteCardVariant==='enhanced'?` · ${gameText('publicProfile.favorite.enhancedBadge')}`:'');
    overlay.querySelector('.public-profile-shell').innerHTML=`
      <div class="public-profile-topbar"><button class="public-profile-back" type="button">← ${esc(gameText('common.back'))}</button><div><div class="public-profile-kicker">${esc(gameText('publicProfile.kicker'))}</div><div class="public-profile-title">${esc(gameText('publicProfile.title'))}</div></div></div>
      <section class="public-profile-hero" data-profile-background="${cosmeticAttr(profile,'backgroundId')}" data-profile-frame="${cosmeticAttr(profile,'frameId')}"><div class="public-profile-cosmetic-background-slot" aria-hidden="true"></div>${avatar}<div><div class="public-profile-name-row"><div class="public-profile-name">${esc(profile.username||gameText('ranking.playerFallback'))}</div><span class="public-profile-name-badge-slot" data-profile-name-badge="${cosmeticAttr(profile,'nameBadgeId')}" aria-hidden="true"></span><span class="public-profile-title-slot" data-profile-title="${cosmeticAttr(profile,'titleId')}" aria-hidden="true"></span></div><div class="public-profile-meta"><span class="public-profile-pill">${esc(gameText(eloGames<10?'ranking.elo.provisional':'ranking.elo.established',{rating:elo.toLocaleString('es-AR')}))}</span><span class="public-profile-pill">${esc(gameText('publicProfile.meta.games',{count:n(s.gamesPlayed).toLocaleString('es-AR')}))}</span>${joined?`<span class="public-profile-pill">${esc(gameText('publicProfile.meta.joined',{date:joined}))}</span>`:''}</div></div></section>
      <section class="public-profile-section public-profile-favorite"><div class="public-profile-favorite-card" data-favorite-card-slot></div><div><h3 class="public-profile-section-title">${esc(gameText('publicProfile.favorite.title'))}</h3><div class="public-profile-favorite-name">${esc(favoriteName||gameText('publicProfile.favorite.emptyTitle'))}</div><div class="public-profile-favorite-copy">${esc(favoriteId?gameText('publicProfile.favorite.publicHelp'):gameText(isOwn?'publicProfile.favorite.emptyOwn':'publicProfile.favorite.emptyOther'))}</div>${isOwn?`<div class="public-profile-favorite-actions"><button type="button" class="public-profile-favorite-btn" data-edit-favorite>${esc(gameText(favoriteId?'publicProfile.favorite.change':'publicProfile.favorite.choose'))}</button>${favoriteId?`<button type="button" class="public-profile-favorite-btn secondary" data-clear-favorite>${esc(gameText('publicProfile.favorite.clear'))}</button>`:''}</div>`:''}</div></section>
      <section class="public-profile-section"><h3 class="public-profile-section-title">${esc(gameText('publicProfile.section.competition'))}</h3><div class="public-profile-grid">${stat(gameText('publicProfile.stat.elo'),elo.toLocaleString('es-AR'),gameText('publicProfile.stat.eloPeak',{rating:n(s.eloPeak||elo).toLocaleString('es-AR')}))}${stat(gameText('publicProfile.stat.wins'),n(s.wins).toLocaleString('es-AR'),gameText('publicProfile.stat.winRate',{rate:wr.toFixed(1)}))}${stat(gameText('publicProfile.stat.pvp'),gameText('publicProfile.stat.record',{wins:n(s.multiplayerWins),losses:n(s.multiplayerLosses)}))}${stat(gameText('publicProfile.stat.solo'),gameText('publicProfile.stat.record',{wins:n(s.soloWins),losses:n(s.soloLosses)}))}${stat(gameText('publicProfile.stat.cup'),n(s.tournamentChampionships).toLocaleString('es-AR'),gameText('publicProfile.stat.tournaments',{count:n(s.tournamentsPlayed)}))}${stat(gameText('publicProfile.stat.time'),formatDuration(n(s.totalDurationMs)))}${stat(gameText('publicProfile.stat.trades'),n(s.tradesCompleted).toLocaleString('es-AR'))}${stat(gameText('publicProfile.stat.abandons'),n(s.abandons).toLocaleString('es-AR'))}</div></section>
      <section class="public-profile-section"><h3 class="public-profile-section-title">${esc(gameText('publicProfile.section.collection'))}</h3><div class="public-profile-grid">${stat(gameText('publicProfile.stat.uniqueCards'),`${n(s.uniqueCards).toLocaleString('es-AR')} / ${POOL_BASELINE.total}`)}${stat(gameText('publicProfile.stat.packsOpened'),n(s.packsOpened).toLocaleString('es-AR'))}${stat(gameText('publicProfile.stat.guaranteedMythics'),n(s.guaranteedMythicsOpened).toLocaleString('es-AR'))}${stat(gameText('publicProfile.stat.classifieds'),n(s.classifiedsCardsPurchased).toLocaleString('es-AR'))}</div></section>
      <section class="public-profile-section"><h3 class="public-profile-section-title">${esc(gameText('publicProfile.section.workshop'))}</h3><div class="public-profile-grid">${stat(gameText('publicProfile.stat.machines'),`${n(profile.workshop?.machinesUnlocked)} / 4`)}${stat(gameText('publicProfile.stat.enhancements'),n(profile.workshop?.enhancementsCrafted).toLocaleString('es-AR'))}${stat(gameText('publicProfile.stat.evolutions'),n(profile.workshop?.cardsEvolved).toLocaleString('es-AR'))}${stat(gameText('publicProfile.stat.mixes'),n(profile.workshop?.industrialMixes).toLocaleString('es-AR'))}</div></section>
      <section class="public-profile-section"><h3 class="public-profile-section-title">${esc(gameText('publicProfile.section.achievements'))}</h3><div class="public-profile-trophies">${achievements}</div></section>
      <div class="public-profile-privacy">${esc(gameText('publicProfile.privacy'))}</div>`;
    overlay.querySelector('.public-profile-back')?.addEventListener('click',close);
    const slot=overlay.querySelector('[data-favorite-card-slot]');if(slot){slot.replaceChildren();const cardNode=favoriteId?renderRealCard(favoriteId,profile):null;if(cardNode)slot.appendChild(cardNode);else{const empty=document.createElement('div');empty.className='public-profile-favorite-empty';empty.textContent=gameText('publicProfile.favorite.emptySlot');slot.appendChild(empty);}}
    if(isOwn){const applyLocalFavorite=id=>{const parsed=parseFavoriteId(id);profile.favoriteCardId=id;profile.favoriteCardBaseId=id?parsed.baseId:'';profile.favoriteCardVariant=id?parsed.variant:'';profile.favoriteCardEnhancementKeyword=id&&parsed.variant==='enhanced'?String(localEnhancements()[parsed.baseId]||''):'';profile.favoriteCardName=id?String(cardDb.getById(parsed.baseId)?.name||parsed.baseId):'';renderProfile(profile);};overlay.querySelector('[data-edit-favorite]')?.addEventListener('click',()=>openFavoritePicker(profile,applyLocalFavorite));overlay.querySelector('[data-clear-favorite]')?.addEventListener('click',()=>openFavoritePicker(profile,applyLocalFavorite));}
  };
  fetchPublicPlayerProfile(targetUid).then(profile=>{if(!profile)throw new Error(gameText('publicProfile.notFound'));renderProfile(profile);}).catch(error=>{console.error('No se pudo cargar Perfil Público:',error);const shell=overlay.querySelector('.public-profile-shell');shell.innerHTML=`<div class="public-profile-topbar"><button class="public-profile-back" type="button">← ${esc(gameText('common.back'))}</button><div><div class="public-profile-kicker">${esc(gameText('publicProfile.kicker'))}</div><div class="public-profile-title">${esc(gameText('publicProfile.title'))}</div></div></div><div class="public-profile-error">${esc(gameText('publicProfile.error'))}</div>`;shell.querySelector('.public-profile-back')?.addEventListener('click',close);});
  return overlay;
}
